import Head from "next/head";
import { Game } from "~/components/Game";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#5f3e8e] to-[#5b61d4]">
        <Game />
      </main>
    </>
  );
}
